---
# MacOS setup script configs
macos_hostname: "mbp-51ew5rz5" # e.g. "mbp-51ew5rz5"
macos_computer_name: "MacBook Pro" # e.g. "MacBook Pro"

# MacOS screenshots
macos_screenshots_dir: "{{ ansible_user_dir }}/Desktop"
macos_screenshots_type: "png"

# Path to common shell scripts
scripts_dir: "{{ playbook_dir }}/scripts"

# Zsh configs
zsh_completions_dir: "{{ ansible_user_dir }}/.zsh/completions"

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Safari
  - Messages
  - Mail
  - Maps
  - Photos
  - FaceTime
  - Calendar
  - Contacts
  - Reminders
  - Notes
  - Freeform
  - TV
  - Music
  - Weather
  - Tips
  - Stocks
  - Shortcuts
  - Podcasts
  - Passwords
  - Notes
  - Home
  - Clock
  - Calculator
  - Stickies
  - Siri
  - Preview
  - Keynote
  - Numbers
  - Pages
  - 'App Store'
  - 'QuickTime Player'
  - 'iPhone Mirroring'
  - 'Find My'
  - 'System Settings'

dockitems_persist:
  - name: "Firefox"
    path: "/Applications/Firefox.app/"
    pos: 3
  - name: "iTerm"
    path: "/Applications/iTerm.app/"
    pos: 4
  - name: "Obsidian"
    path: "/Applications/Obsidian.app/"
    pos: 5
  - name: "Visual Studio Code"
    path: "/Applications/Visual\ Studio\ Code.app/"
    pos: 6
  - name: "1Password"
    path: "/Applications/1Password.app/"
    pos: 7
  - name: "Deezer"
    path: "/Applications/Deezer.app/"
    pos: 8
  - name: "Telegram"
    path: "/Applications/Telegram.app/"
    pos: 9

homebrew_cask_accept_external_apps: true
homebrew_upgrade_all_packages: true

homebrew_installed_packages:
  - autoconf
  - automake
  - make
  - bfg                        # Remove large files or passwords from Git history like git-filter-branch
  - coreutils
  - direnv                     # Load/unload environment variables based on $PWD
  - dnsmasq                    # Lightweight DNS forwarder and DHCP server
  - fd
  - htop
  - rcm                        # RC file (dotfile) management
  - readline                   # Library for command-line editing
  - tmux
  - vim
  - unzip
  - zlib
  - xz
  - universal-ctags
  - gpg
  - curl
  - httpie                     # User-friendly cURL replacement (command-line HTTP client)
  - ssh-copy-id                # Add a public key to a remote machine's authorized_keys file
  - openssl
  - pv                         # Monitor data's progress through a pipe
  - wget
  - tree
  - bat                        # Clone of cat(1) with syntax highlighting and Git integration
  - tlrc                       # Simplified and community-driven man pages
  - ncdu                       # NCurses Disk Usage
  - 1password-cli
  - gh
  - shellcheck
  - sha2
  - font-cascadia-code
  - font-fira-code
  - font-ibm-plex-mono
  - docker-credential-helper
  - dive                       # Tool for exploring each layer in a docker image
  - zsh-syntax-highlighting
  - zsh-autosuggestions
  - sqlite3
  - tcl-tk@8
  - smartmontools
  - fastfetch
  - cpufetch
  - wrk                        # HTTP benchmarking tool
  - iperf                      # Tool to measure maximum TCP and UDP bandwidth
  - nmap
  - watch
  - mise

homebrew_taps: []

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password
  - google-chrome
  - ngrok
  - telegram
  - visual-studio-code
  - vlc
  - launchcontrol
  - mos
  - jetbrains-toolbox                 # Use cloud sync for settings retrieveing (check README.md)
  - obsidian                          # Application configurations always stored in the vault
  - deezer
  - crossover
  - handbrake
  - cyberduck
  - xnconvert
  - postman
  - macs-fan-control
  - transmission
  - google-drive
  - zoom
  - microsoft-teams
  - proton-drive
  - proton-mail
  - protonvpn

# Wheter install VSCode plugins and set defined settings templates.
configure_vscode: true
vscode_extension_dir: "~/.vscode/extensions"
vscode_extensions:
  - redhat.ansible
  - redhat.vscode-xml
  - redhat.vscode-yaml
  - ms-vscode.cmake-tools
  - ms-vscode.cpptools-extension-pack
  - ms-azuretools.vscode-docker
  - ms-vscode.hexeditor
  - ms-vscode.makefile-tools
  - ms-python.vscode-pylance
  - ms-python.python
  - ms-python.debugpy
  - ms-vscode-remote.vscode-remote-extensionpack
  - ms-vscode-remote.remote-ssh-edit
  - ms-vscode.remote-explorer
  - ms-azuretools.vscode-docker
  - wholroyd.jinja
  - alefragnani.bookmarks
  - twxs.cmake
  - vadimcn.vscode-lldb
  - mikestead.dotenv
  - usernamehw.errorlens
  - dbaeumer.vscode-eslint
  - eamodio.gitlens
  - yzhang.markdown-all-in-one
  - yzane.markdown-pdf
  - esbenp.prettier-vscode
  - mechatroner.rainbow-csv
  - timonwong.shellcheck
  - gruntfuggly.todo-tree
  - gediminaszlatkus.ctags-companion
  - pkief.material-icon-theme
  - mongodb.mongodb-vscode
  - anthropic.claude-code
  - parallelsdesktop.parallels-desktop

xattr_remove_apps:
  - Mos.app

# Scripts set the default settings for the application
app_defaults_scripts:
  - name: "Global"
    script: "{{ scripts_dir }}/defaults/global"
    restart: ["Finder", "Dock"]

  - name: "Mos"
    script: "{{ scripts_dir }}/defaults/mos"
    restart: ["Mos"]

  - name: "NextDNS"
    script: "{{ scripts_dir }}/defaults/nextdns"
    restart: ["NextDNS"]
    vars:
      NEXTDNS_PROFILE_ID: "123abc" # https://my.nextdns.io/

# Git configs
git_user_name: "John Doe"
git_user_email: john_doe@example.com
git_ssh_key_name: default
# https://github.com/settings/tokens
git_github_token: your_personal_token

# Github configs
github_add_ssh_key: true
github_force_ssh_key: true # Replace existing
github_ssh_key_name: default
github_ssh_key_type: "ed25519"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks:
  - tasks/screenshots.yml
  - tasks/1password.yml
