---
# MacOS setup script configs
macos_hostname: "macbook-pro"
macos_computer_name: "MacBook Pro"

# MacOS screenshots
macos_screenshots_dir: "{{ ansible_env.HOME }}/Documents/Screenshots"
macos_screenshots_type: "png"

# Path to common shell scripts
scripts_dir: "{{ playbook_dir }}/scripts"

# Zsh configs
zsh_completions_dir: "{{ ansible_env.HOME }}/.zsh/completions"

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Safari
  - Messages
  - Mail
  - Maps
  - Photos
  - FaceTime
  - Calendar
  - Contacts
  - Reminders
  - Notes
  - Freeform
  - TV
  - Music
  - Weather
  - Tips
  - Stocks
  - Shortcuts
  - Podcasts
  - Passwords
  - Notes
  - Home
  - Clock
  - Calculator
  - Stickies
  - Siri
  - Preview
  - Keynote
  - Numbers
  - Pages
  - 'App Store'
  - 'QuickTime Player'
  - 'iPhone Mirroring'
  - 'Find My'
  - 'System Settings'

dockitems_persist:
  - name: "Firefox"
    path: "/Applications/Firefox.app/"
    pos: 3
  - name: "iTerm"
    path: "/Applications/iTerm.app/"
    pos: 4
  - name: "Obsidian"
    path: "/Applications/Obsidian.app/"
    pos: 5
  - name: "Visual Studio Code"
    path: "/Applications/Visual\ Studio\ Code.app/"
    pos: 6
  - name: "Docker"
    path: "/Applications/Docker.app/"
    pos: 7
  - name: "1Password"
    path: "/Applications/1Password.app/"
    pos: 8
  - name: "Spotify"
    path: "/Applications/Spotify.app/"
    pos: 9
  - name: "Telegram"
    path: "/Applications/Telegram.app/"
    pos: 10

homebrew_cask_accept_external_apps: true

homebrew_installed_packages:
  - autoconf
  - automake
  - make
  - gcc
  - bfg                        # Remove large files or passwords from Git history like git-filter-branch
  - coreutils
  - direnv                     # Load/unload environment variables based on $PWD
  - dnsmasq                    # Lightweight DNS forwarder and DHCP server
  - fzf                        # Command-line fuzzy finder written in Go
  - mcfly                      # Shell history search
  - gnu-time
  - htop
  - rcm                        # RC file (dotfile) management
  - readline                   # Library for command-line editing
  - tmux
  - vim
  - unzip
  - zlib
  - xz
  - universal-ctags
  - gpg
  - curl
  - httpie                     # User-friendly cURL replacement (command-line HTTP client)
  - pngpaste                   # Paste PNG into files
  - ssh-copy-id                # Add a public key to a remote machine's authorized_keys file
  - readline                   # Library for command-line editing
  - openssl
  - pv                         # Monitor data's progress through a pipe
  - wget
  - tree
  - bat                        # Clone of cat(1) with syntax highlighting and Git integration
  - tldr                       # Simplified and community-driven man pages
  - jq
  - ncdu                       # NCurses Disk Usage
  - dive                       # Tool for exploring each layer in a docker image
  - gh
  - shellcheck
  - sha2
  - font-cascadia-code
  - font-fira-code
  - font-ibm-plex-mono
  - 1password-cli
  - colima
  - docker
  - docker-compose
  - docker-buildx
  - docker-credential-helper
  # - wrk                        # HTTP benchmarking tool
  # - iperf                      # Tool to measure maximum TCP and UDP bandwidth
  # - nmap
  # - watchman
  # - bash-completion
  # - doxygen
  # - gettext
  # - gifsicle
  # - siege
  # - tig
  # - libevent
  # - awscli
  # - azure-cli
  # - google-cloud-sdk

homebrew_taps: []

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - 1password                         # Requires additional configuration
  - google-chrome
  - firefox
  - iterm2                            # Configuration will be retrieved from iCloud. Install shell integration (optional)
  - ngrok                             # Requires additional configuration
  - telegram
  - visual-studio-code
  - vlc
  - launchcontrol
  - aldente                           # Manual configuration required at first app launch (check README.md)
  - tg-pro                            # Manual configuration required at first app launch (check README.md)
  - mos                               # com.apple.quarantine xattr removed, default settings applied
  - jetbrains-toolbox                 # Use cloud sync for settings retrieveing (check README.md)
  - logi-options+
  - obsidian                          # Application configurations always stored in the vault
  - spotify
  - qbittorrent                       # com.apple.quarantine xattr removed
  - crossover
  - handbrake
  - cyberduck
  - mullvadvpn
  - xnconvert
  - postman
  - foxitreader
  # - docker

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 497799835, name: "Xcode" }
  - { id: 462054704, name: "Microsoft Word" }
  - { id: 462058435, name: "Microsoft Excel" }
  - { id: 462062816, name: "Microsoft PowerPoint" }
  - { id: 985367838, name: "Microsoft Outlook" }

mas_uninstalled_apps:
  - { id: 682658836, name: "GarageBand" }

# Wheter install VSCode plugins and set defined settings templates.
configure_vscode: true
vscode_extension_dir: "~/.vscode/extensions"
vscode_extensions:
  - redhat.ansible
  - redhat.vscode-xml
  - redhat.vscode-yaml
  - ms-vscode.cmake-tools
  - ms-vscode.cpptools-extension-pack
  - ms-azuretools.vscode-docker
  - ms-vscode.hexeditor
  - ms-vscode.makefile-tools
  - ms-python.vscode-pylance
  - ms-python.python
  - ms-python.debugpy
  - ms-vscode-remote.vscode-remote-extensionpack
  - ms-vscode-remote.remote-ssh-edit
  - ms-vscode.remote-explorer
  - ms-vscode.vscode-serial-monitor
  - wholroyd.jinja
  - dan-c-underwood.arm
  - alefragnani.bookmarks
  - twxs.cmake
  - vadimcn.vscode-lldb
  - firefox-devtools.vscode-firefox-debug
  - mikestead.dotenv
  - usernamehw.errorlens
  - dbaeumer.vscode-eslint
  - eamodio.gitlens
  - yzhang.markdown-all-in-one
  - yzane.markdown-pdf
  - esbenp.prettier-vscode
  - mechatroner.rainbow-csv
  - timonwong.shellcheck
  - jock.svg
  - gruntfuggly.todo-tree
  - mshr-h.veriloghdl
  - gediminaszlatkus.ctags-companion
  - zhuangtongfa.material-theme
  - pkief.material-icon-theme

xattr_remove_apps:
  - qBittorrent.app
  - Mos.app

# Scripts set the default settings for the application
app_defaults_scripts:
  - { name: "Global", script: "{{ scripts_dir }}/defaults/global", restart: ["Finder", "Dock"] }
  - { name: "Aldente", script: "{{ scripts_dir }}/defaults/aldente", restart: ["Aldente"] }
  - { name: "TG Pro", script: "{{ scripts_dir }}/defaults/tg-pro", restart: ["TG Pro"] }
  - { name: "Mos", script: "{{ scripts_dir }}/defaults/mos", restart: ["Mos"] }

# Colima settings
colima_profile: default
colima_cpu: 8
colima_memory: 16
colima_disk: 256
colima_vm_type: vz

# Git configs
git_user_name: "Ilya Sirotin"
git_user_email: ilyasirotin.we@gmail.com
git_ssh_key_name: default
# https://github.com/settings/tokens
git_github_token: you_personal_token

# Github configs
github_add_ssh_key: true
github_force_ssh_key: true # Replace existing
github_ssh_key_name: default
github_ssh_key_type: "ed25519"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks:
  - tasks/ssh.yml
  - tasks/github.yml
  - tasks/dotfiles.yml
  - tasks/screenshots.yml
  - tasks/clean.yml
