---
- name: Host configuration
  hosts: local

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration
      ansible.builtin.include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
      when: ansible_os_family == "Darwin"
    - role: dnsmasq
      tags: ['dnsmasq']
    - role: git
      tags: ['git']
    - role: vscode
      tags: ['vscode']

  tasks:
    - ansible.builtin.import_tasks: tasks/scripts.yml
      tags: ['scripts']

    - ansible.builtin.import_tasks: tasks/zsh.yml
      tags: ['shell', 'zsh']
      when: ansible_os_family == "Darwin"

    - ansible.builtin.import_tasks: tasks/bash.yml
      tags: ['shell', 'bash']
      when: ansible_os_family == "RedHat"

    - ansible.builtin.import_tasks: tasks/ssh.yml
      tags: ['ssh']

    - ansible.builtin.import_tasks: tasks/vim.yml
      tags: ['vim']

    - ansible.builtin.import_tasks: tasks/github.yml
      tags: ['github']

    - ansible.builtin.import_tasks: tasks/1password.yml
      tags: ['1password']
