---
- name: Ensure 1Password is installed
  community.general.homebrew_cask:
    name: "1password"
    state: present

- name: Ensure 1Password CLI is installed
  community.general.homebrew:
    name: "1password-cli"
    state: present

- name: Symlink 1Password agent sock
  block:
    - name: Ensure .1password config directory exist
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.1password"
        state: directory
    - name: Symlink agent.sock
      ansible.builtin.include_role:
        name: symlink
      vars:
        symlink_src: "{{ ansible_user_dir }}/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock"
        symlink_dst: "{{ ansible_user_dir }}/.1password/agent.sock"

- name: Create 1Password SSH agent config from template
  ansible.builtin.template:
    src: ssh-agent-config.toml.j2
    dest: "{{ playbook_dir }}/files/ssh-agent-config.toml"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"

- name: Symlink 1Password SSH agent config
  block:
    - name: Ensure 1Password config directory exist
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.config/1Password/ssh"
        state: directory
    - name: Symlink ssh agent config
      ansible.builtin.include_role:
        name: symlink
      vars:
        symlink_src: "{{ playbook_dir }}/files/ssh-agent-config.toml"
        symlink_dst: "{{ ansible_user_dir }}/.config/1Password/ssh/agent.toml"
