---
- name: Create 1Password SSH agent config from template
  ansible.builtin.template:
    src: "{{ ansible_os_family }}_ssh_agent_config.toml.j2"
    dest: "{{ ansible_user_dir }}/.config/1Password/ssh/agent.toml"
