---
- name: Check brew installed
  ansible.builtin.command: "which brew"
  register: brew_state
  ignore_errors: true
  check_mode: false
  changed_when: false

- name: Perform brew cleanup
  ansible.builtin.command:
    cmd: "brew cleanup"
  when: brew_state.rc == 0

- name: Perform brew cache cleanup
  ansible.builtin.command:
    cmd: "brew autoremove"
  when: brew_state.rc == 0
