---
- name: Get the path to bash
  ansible.builtin.command:
    cmd: which bash
  become: false
  register: shell_path

- name: Ensure bash is in allowed shells
  ansible.builtin.lineinfile:
    path: /etc/shells
    line: "{{ shell_path.stdout }}"
  become: true

- name: Set bash as the default shell
  ansible.builtin.shell:
    cmd: chsh -s $(which bash) {{ lookup('env', 'USER') }}
  become: true

- name: Create bash configs from templates
  ansible.builtin.template:
    src: "{{ ansible_facts['os_family'] }}_{{ item }}.j2"
    dest: "{{ ansible_facts['user_dir'] }}/.{{ item }}"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_gid'] }}"
  loop:
    - bashrc
    - bash_profile
