---
- name: Ensure required homebrew packages are installed
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - colima
    - docker
    - docker-compose
    - docker-buildx

- name: List colima instances
  ansible.builtin.command: colima list --json
  register: colima_instances_result
  changed_when: false

- name: Format instances
  ansible.builtin.set_fact:
    colima_instances: "{{ colima_instances_result.stdout | default('{}', true) | from_json }}"

- name: Create docker plugins directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.docker/cli-plugins"
    state: directory

- name: Symlink docker compose
  ansible.builtin.include_role:
    name: symlink
  vars:
    symlink_src: "{{ homebrew_prefix }}/opt/docker-compose/bin/docker-compose"
    symlink_dst: "{{ ansible_env.HOME }}/.docker/cli-plugins/docker-compose"

- name: Symlink docker build
  ansible.builtin.include_role:
    name: symlink
  vars:
    symlink_src: "{{ homebrew_prefix }}/opt/docker-buildx/bin/docker-buildx"
    symlink_dst: "{{ ansible_env.HOME }}/.docker/cli-plugins/docker-buildx"

- name: Start new instance
  ansible.builtin.command:
    cmd: "colima start \
      --profile {{ colima_profile }} \
      --activate \
      --arch aarch64 \
      --cpu {{ colima_cpu }} \
      --memory {{ colima_memory }} \
      --disk {{ colima_disk }} \
      --mount {{ ansible_env.HOME }}:w \
      --mount-inotify \
      --ssh-agent \
      --vm-type {{ colima_vm_type }} \
      --vz-rosetta"
  when: "colima_instances.status is not defined"
  register: colima_start_result
  changed_when: colima_start_result.rc == 0

- name: Run existing stopped instance
  ansible.builtin.command: colima start
  when: "colima_instances.status | default == 'Stopped'"
  register: colima_start_result
  changed_when: colima_start_result.rc == 0

- name: Start colima brew service
  community.general.homebrew_services:
    name: colima
    state: present

- name: Get completions directory status
  ansible.builtin.stat:
    path: "{{ zsh_completions_dir }}"
  register: completions_dir_state
  changed_when: false

- name: Generate colima completions script
  ansible.builtin.shell:
    cmd: "colima completion zsh > {{ zsh_completions_dir }}/_colima"
  when: completions_dir_state.stat.exists
