---
- name: Make script executable
  ansible.builtin.file:
    dest: "{{ item.script }}"
    mode: a+x

- name: Quit application
  ansible.builtin.command:
    cmd: "osascript -e 'tell application \"{{ item.name }}\" to quit'"
  changed_when: false

- name: Apply defaults
  ansible.builtin.command:
    cmd: "{{ item.script }}"

- name: Start application
  ansible.builtin.command:
    cmd: "open -a \"{{ item.name }}\""
  changed_when: false
