---

- name: Create dotfiles from templates
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ playbook_dir }}/files/{{ item | regex_replace('\\.j2$', '') }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
  loop:
    - vimrc.j2

- name: Link dotfiles
  ansible.builtin.include_role:
    name: symlink
  vars:
    symlink_src: "{{ playbook_dir }}/files/{{ item }}"
    symlink_dst: "{{ ansible_user_dir }}/.{{ item }}"
  loop:
    - "vimrc"
