---
- name: Check NVM already installed
  ansible.builtin.command:
    cmd: "command -v nvm"
  register: nvm_status
  failed_when: false

- name: Install NVM
  when: nvm_status.rc != 0
  block:
    - name: Download NVM installation script
      ansible.builtin.get_url:
        url: "https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh"
        dest: "{{ ansible_user_dir }}/nvm"
        mode: "0755"

    - name: Run NVM installation script
      ansible.builtin.command:
        cmd: "{{ ansible_user_dir }}/nvm"

    - name: Remove temporary files
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/nvm"
        state: absent
