---
- name: "Make osx-setup executable"
  ansible.builtin.file:
    dest: "{{ scripts_dir }}/osx-setup"
    mode: a+x

- name: Run macOS setup script
  ansible.builtin.shell: |
    HOSTNAME="{{ macos_hostname }}" COMPUTER_NAME="{{ macos_computer_name }}" {{ scripts_dir }}/osx-setup
  become: true
