---
- name: "Check screenshots directory"
  ansible.builtin.stat:
    path: "{{ macos_screenshots_dir }}"
  register: screenshots_dir

- name: "Create screenshots directory"
  ansible.builtin.file:
    path: "{{ macos_screenshots_dir }}"
    state: directory
  when: not screenshots_dir.stat.exists

- name: Set screenshots default location
  ansible.builtin.shell: |
    defaults write com.apple.screencapture location "{{ macos_screenshots_dir }}" &&\
    killall SystemUIServer

- name: Save screenshot in given type
  ansible.builtin.shell: |
    defaults write com.apple.screencapture type -string "png"
