---
- name: Check .ssh folder exist
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.ssh"
    state: directory

- name: Create ssh config from template
  ansible.builtin.template:
    src: "ssh_config.j2"
    dest: "{{ ansible_user_dir }}/.ssh/config"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
