---
- name: Check .ssh folder exist
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.ssh"
    state: directory

- name: Link ssh config
  ansible.builtin.include_role:
    name: symlink
  vars:
    symlink_src: "{{ playbook_dir }}/files/ssh-config"
    symlink_dst: "{{ ansible_user_dir }}/.ssh/config"
