---
- name: Get the path to ZSH
  ansible.builtin.command:
    cmd: which zsh
  become: false
  register: shell_path

- name: Ensure zsh is in allowed shells
  ansible.builtin.lineinfile:
    path: /etc/shells
    line: "{{ shell_path.stdout }}"
  become: true

- name: Set ZSH as the default shell
  ansible.builtin.shell:
    cmd: chsh -s $(which zsh) {{ lookup('env', 'USER') }}
  become: true

- name: Create completion scripts directory
  ansible.builtin.file:
    path: "{{ ansible_facts['user_dir'] }}/.zsh/completions"
    state: directory

- name: Create zsh configs from templates
  ansible.builtin.template:
    src: "{{ ansible_facts['os_family'] }}_{{ item }}.j2"
    dest: "{{ ansible_facts['user_dir'] }}/.{{ item }}"
    owner: "{{ ansible_facts['user_id'] }}"
    group: "{{ ansible_facts['user_gid'] }}"
  loop:
    - zshrc
    - zprofile
