---
- name: Check for vscode
  ansible.builtin.command: "code --version"
  register: vscode_installed
  ignore_errors: true
  check_mode: false
  changed_when: false

- name: List installed extensions
  ansible.builtin.command: "code --list-extensions"
  register: vscode_extensions_installed
  when: vscode_installed.rc == 0
  check_mode: false
  changed_when: false

- name: Install vscode extensions
  ansible.builtin.command:
    cmd: "code --install-extension {{ item }}"
  loop: "{{ vscode_extensions }}"
  when: vscode_installed.rc == 0 and item not in vscode_extensions_installed.stdout_lines
  changed_when: vscode_extensions_installed.rc == 0

- name: Load OS-specific variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_os_family }}.yml"
      paths:
        - "vars"

- name: Ensure VSCode configs directory exists
  file:
    path: "{{ vscode_configs_path }}"
    state: directory
    mode: '0755'

- name: Copy vscode settings.json file
  ansible.builtin.copy:
    src: settings.json
    dest: "{{ vscode_configs_path }}/settings.json"
    mode: "0644"

- name: Copy vscode keybindings.json file
  ansible.builtin.copy:
    src: keybindings.json
    dest: "{{ vscode_configs_path }}/keybindings.json"
    mode: "0644"
