#!/bin/bash

alias ll="ls -lhF"
alias la="ls -lhaF"

# Show xattr
alias lx="ls -@la"

# Docker
alias dvpurge="docker volume rm \$(docker volume ls -qf dangling=true)"

# Git aliases
alias gs="git status"
alias gc="git commit"
alias gp="git pull"
alias gcam="git commit -am"
alias gl="git log --graph --pretty=format:\"%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset\" --abbrev-commit"

alias mann="tldr"

# docker
alias dvpurge="docker volume rm \$(docker volume ls -qf dangling=true)"

# zsh
alias zshcc="rm ~/.zcompdump && autoload -Uz compinit && compinit"
