#!/bin/bash

# Delete a given line number in the known_hosts file
knownrm() {
 re='^[0-9]+$'
 if ! [[ $1 =~ $re ]] ; then
   echo "error: line number missing" >&2;
 else
   sed -i '' "$1d" ~/.ssh/known_hosts
 fi
}

# Enter a running Docker container
function denter() {
 if [[ ! "$1" ]] ; then
     echo "You must supply a container ID or name."
     return 0
 fi

 docker exec -it "$1" bash
 return 0
}

# Run php composer inside docker container
composer() {
    docker run \
      --rm \
      --interactive \
      --tty \
      -v "$(pwd):/app" \
      -v "$COMPOSER_HOME:/tmp" \
      -e COMPOSER_HOME="$COMPOSER_HOME" composer/composer "$@"
}

# Run php inside docker container
php() {
    docker run \
      --rm \
      --interactive \
      --tty \
      -v "$(pwd):/app" \
      -w /app \
      -p 8080:8080 php:"${PHP_VERSION}"-cli php "$@"
}
