eval "$(/opt/homebrew/bin/brew shellenv)"

# Added by Toolbox App
export PATH="$PATH:/Users/ilya/Library/Application Support/JetBrains/Toolbox/scripts"

# rbenv
eval "$(rbenv init - --no-rehash zsh)"

# Import aliases, exports and functions
for file in ~/.{zsh_aliases,zsh_exports,zsh_functions}; do
  [ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;
