# Colorized terminal
unset LSCOLORS
export CLICOLOR=1
export CLICOLOR_FORCE=1

# Custom prompt
autoload -U colors && colors
NL=$'\n'
PS1="%F{green}%n%f@%F{yellow}%m%f %F{cyan}%~%f${NL}>%f "

# Don't require escaping globbing characters in zsh.
unsetopt nomatch

# Completions
autoload -Uz compinit && compinit
# Case insensitive
zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*'

# Ngrok completions
if command -v ngrok &>/dev/null; then
  eval "$(ngrok completion)"
fi

# Colima
fpath=(~/.zsh/completions $fpath)
autoload -U compinit
compinit

# export COLIMA_VM="default"
# export COLIMA_VM_SOCKET="${HOME}/.colima/${COLIMA_VM}/docker.sock"
# export DOCKER_HOST="unix://${COLIMA_VM_SOCKET}"

# 1Password ssh agent
export SSH_AUTH_SOCK=~/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock

# 1Password plugins
source ~/.config/op/plugins.sh

# 1Password completions
# eval "$(op completion zsh)"; compdef _op op

# Tell homebrew to not autoupdate every single time I run it (just once a week).
export HOMEBREW_AUTO_UPDATE_SECS=604800

# Use bat instead of cat
alias rcat="$(which cat)"

alias cat="$(which bat)"
export BAT_THEME="ansi-dark"

# Set up fzf key bindings and fuzzy completion
source <(fzf --zsh)

export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS"\
" --exact"\
" --height 50% --layout reverse --border --no-mouse"\
" --color=bg:0,fg:7,hl:3"\
" --color=bg+:8,fg+:7,hl+:11"\
" --color=info:3,border:3,prompt:4"\
" --color=pointer:0,marker:9,spinner:9,header:1"

FD_OPTIONS="--follow --exclude .git --exclude node_modules"
export FZF_DEFAULT_COMMAND="git ls-files --cached --others --exclude-standard | fd --type f --type l $FD_OPTIONS"
export FZF_CTRL_T_COMMAND="fd $FD_OPTIONS"
export FZF_ALT_C_COMMAND="fd --type d $FD_OPTIONS"

# Zsh syntax highlighting
source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Zsh suggestions
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# iTerm2 shell integration
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Pyenv
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

eval "$(pyenv virtualenv-init -)"

# Sdkman
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
