# Colorized terminal
unset LSCOLORS
export CLICOLOR=1
export CLICOLOR_FORCE=1

# Init completions
autoload -Uz compinit
compinit

# Shell completions scripts
fpath=(/Users/ilya/.docker/completions $fpath)
fpath=(~/.zsh/completions $fpath)

# Custom prompt
autoload -U colors && colors
NL=$'\n'
PS1="%F{green}%n%f@%F{yellow}%m%f %F{cyan}%~%f${NL}>%f "

# Don't require escaping globbing characters in zsh.
unsetopt nomatch

# Case insensitive
zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*'

# Ngrok completions
if command -v ngrok &>/dev/null; then
  eval "$(ngrok completion)"
fi

# 1Password ssh agent
export SSH_AUTH_SOCK=~/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock

# 1Password plugins
source ~/.config/op/plugins.sh

# Tell homebrew to not autoupdate every single time I run it (just once a week).
export HOMEBREW_AUTO_UPDATE_SECS=604800

# Use bat instead of cat
alias rcat="$(which cat)"

alias cat="$(which bat)"
export BAT_THEME="ansi-dark"

# Zsh syntax highlighting
source $(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Zsh suggestions
source $(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh

# iTerm2 shell integration
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Pyenv
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# Sdkman
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"
