---
- name: Check {{ symlink_dst }}
  ansible.builtin.stat:
    path: "{{ symlink_dst }}"
  register: link_stat

- name: Remove {{ symlink_dst }}
  ansible.builtin.file:
    path: "{{ symlink_dst }}"
    state: absent
  when: link_stat.stat.exists and not link_stat.stat.islnk

- name: Link {{ symlink_src }}
  ansible.builtin.file:
    src: "{{ symlink_src }}"
    dest: "{{ symlink_dst }}"
    state: link
    mode: "0644"
    force: true
  become: false
