#!/bin/bash

defaults write -app "Aldente" chargeVal -int 80

defaults write -app "Aldente" exitInhibitCharge -int 1

defaults write -app "Aldente" heatProtectMode -int 1

defaults write -app "Aldente" launchAtLogin -int 1

defaults write -app "Aldente" lpmPreference -int 1

defaults write -app "Aldente" magsafeControl -int 0

defaults write -app "Aldente" maxTemperature -int 35

defaults write -app "Aldente" menuBarIconStyle -int 2

defaults write -app "Aldente" noMenubarIcon -int 0

defaults write -app "Aldente" popoverWidgets -array powerflow highAppUsage

defaults write -app "Aldente" sailingLevel -int 10

defaults write -app "Aldente" showDockIcon -int 0

defaults write -app "Aldente" showPercentage -int 0

defaults write -app "Aldente" showPercentagePopover -int 1

defaults write -app "Aldente" sleepInhibitCharge -int 1

defaults write -app "Aldente" showGUIonStartup -int 0

defaults write -app "Aldente" uiCollapseState -dict-add \
  "bi_batteryhealth" -int 1   \
  "bi_batteryspecs" -int 1    \
  "bi_chargerspecs" -int 1    \
  "bi_electricalspecs" -int 0
