#!/bin/bash

###############################################################################
# General                                                                     #
###############################################################################

# Automatically quit printer app once the print jobs complete
defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true

# Disable smart quotes and dashes as they’re annoying when typing code
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

###############################################################################
# Finder                                                                      #
###############################################################################

defaults write com.apple.finder ShowPathbar -bool true

defaults write com.apple.finder ShowStatusBar -bool true

defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

defaults write com.apple.finder NewWindowTarget -string "PfLo" && \
defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}"

defaults write -g NSNavRecentPlacesLimit -int 5

defaults write -g AppleShowAllExtensions -bool false

defaults write com.apple.finder AppleShowAllFiles false

# Display full POSIX path as Finder window title
defaults write com.apple.finder _FXShowPosixPathInTitle -bool false

defaults write com.apple.finder QuitMenuItem -bool false

# Avoids creation of .DS_Store and AppleDouble files on network volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

# Avoids creation of .DS_Store and AppleDouble files on usb volumes
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

defaults write NSGlobalDomain com.apple.springing.enabled -bool true

defaults write NSGlobalDomain com.apple.springing.delay -float 0.5

defaults write com.apple.finder FXPreferredViewStyle -string "clmv"

###############################################################################
# Dock                                                                        #
###############################################################################

defaults write com.apple.dock autohide -bool true

defaults write com.apple.dock show-recents -bool false

defaults write com.apple.dock magnification -int 1 &&\
defaults write com.apple.dock largesize -int 84

defaults write com.apple.dock "show-recents" -int 0

###############################################################################
# Trackpad, mouse, keyboard, Bluetooth accessories, and input                 #
###############################################################################

# Trackpad: Haptic feedback (light, silent clicking)
defaults write com.apple.AppleMultitouchTrackpad FirstClickThreshold -int 0
defaults write com.apple.AppleMultitouchTrackpad ActuationStrength -int 0

defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

defaults write -g ApplePressAndHoldEnabled -bool false

###############################################################################
# Activity Monitor                                                            #
###############################################################################

# Show the main window when launching Activity Monitor
defaults write com.apple.ActivityMonitor OpenMainWindow -int 1

# Show all processes in Activity Monitor
defaults write com.apple.ActivityMonitor ShowCategory -int 101

defaults write com.apple.ActivityMonitor UpdatePeriod -int 5

###############################################################################
# Kill/restart affected system applications and services                      #
###############################################################################

# Restart affected applications if `--no-restart` flag is not present.
if [[ ! ($* == *--no-restart*) ]]; then
  for app in "cfprefsd" "SystemUIServer"; do
    killall "${app}" > /dev/null 2>&1
  done
fi
