syntax on                   " enable syntax highlighting
set nobackup                " don't create pointless backup files; Use VCS instead
set autoread                " watch for file changes
set number                  " show line numbers
set showcmd                 " show selection metadata
set showmode                " show INSERT, VISUAL, etc. mode
set showmatch               " show matching brackets
set autoindent smartindent  " auto/smart indent
set smarttab                " better backspace and tab functionality
set scrolloff=5             " show at least 5 lines above/below
filetype on                 " enable filetype detection
filetype indent on          " enable filetype-specific indenting
filetype plugin on          " enable filetype-specific plugins

" cursor line visual indication
set cursorline
highlight CursorLine cterm=none ctermbg=17 guibg=#001A33

" column-width visual indication
set colorcolumn=121
highlight ColorColumn ctermbg=235 guibg=#2E2E2E

" tabs and indenting
set autoindent              " auto indenting
set smartindent             " smart indenting
set expandtab               " spaces instead of tabs
set tabstop=2               " 2 spaces for tabs
set shiftwidth=2            " 2 spaces for indentation

" bells
set noerrorbells            " turn off audio bell
set visualbell              " but leave on a visual bell

" search
set hlsearch                " highlighted search results
set showmatch               " show matching bracket

" clipboard
set clipboard=unnamed       " allow yy, etc. to interact with OS X clipboard
