---
- name: Install homebrew packages
  community.general.homebrew:
    name: dnsmasq
    state: present
  notify:
    - Clear homebrew cache
    - Restart Dnsmasq

- name: Copy Dnsmasq configuration in place
  ansible.builtin.template:
    src: dnsmasq.conf.j2
    dest: "{{ homebrew_prefix }}/etc/dnsmasq.conf"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    mode: "0644"
  notify:
    - Restart Dnsmasq

- name: Ensure resolver directory exists
  ansible.builtin.file:
    dest: /etc/resolver
    state: directory
    mode: "0755"
  become: true

- name: Configure Dnsmasq resolver
  ansible.builtin.copy:
    src: resolver.conf
    dest: "/etc/resolver/{{ item.domain }}"
    mode: "0644"
  loop: "{{ dnsmasq_hosts }}"
  become: true
