---
- name: Print default PHP version
  ansible.builtin.debug:
    var: php_default_version

- name: Ensure required taps are added
  community.general.homebrew_tap:
    tap: "{{ item }}"
    state: present
  loop:
    - shivammathur/php
    - shivammathur/extensions

- name: Install PHP versions
  community.general.homebrew:
    name: "shivammathur/php/php@{{ item }}"
    state: present
  loop: "{{ php_versions }}"

- name: Check composer already installed
  ansible.builtin.stat:
    path: "/usr/local/bin/composer"
  register: composer_bin

- name: Install composer
  ansible.builtin.get_url:
    url: "https://getcomposer.org/download/latest-stable/composer.phar"
    dest: "/usr/local/bin/composer"
    mode: "0755"
  become: true
  when: php_install_composer and not composer_bin.stat.exists

- name: Install PECL extensions via brew
  ansible.builtin.include_tasks: pecl-brewed.yml
  loop: "{{ php_versions }}"
  loop_control:
    loop_var: php_version
