---
- name: Install PECL extension
  community.general.pear:
    executable: "{{ php_installation_location.path }}/bin/pecl"
    name: "pecl/{{ php_pecl_extension.name }}-{{ php_pecl_extension.version }}"
    state: present
  environment: "{{ php_pecl_extension.envs }}"

- name: Remove automatic PECL extension installation
  ansible.builtin.lineinfile:
    path: "{{ homebrew_prefix }}/etc/php/{{ php_version }}/php.ini"
    line: "extension=\"{{ php_pecl_extension.name }}.so\""
    mode: "0644"
    state: absent

- name: Enable PECL extension
  ansible.builtin.lineinfile:
    path: "{{ homebrew_prefix }}/etc/php/{{ php_version }}/conf.d/{{ php_pecl_extension.name }}.ini"
    line: "extension={{ homebrew_prefix }}/lib/php/pecl/{{ php_pecl_extension_dir.stdout | basename }}/{{ php_pecl_extension.name }}.so"
    mode: "0644"
    create: true
